name: Gatsby Publish

on:
  push:
    branches:
      [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci --legacy-peer-deps
      - run: npm run test
        env:
          CI: true
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci --legacy-peer-deps
      - run: ./scripts/preprocess-publications.js
      - run: ./scripts/preprocess-talks.js
      - run: npm run build
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_SEARCH_ONLY_API_KEY: ${{ secrets.ALGOLIA_SEARCH_ONLY_API_KEY }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          BEAM_ID: ${{secrets.BEAM_ID}}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          NODE_ENV: production
          GATSBY_ACTIVE_ENV: production
      # see https://github.com/puppeteer/puppeteer/issues/12818
      - name: Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - run: npm run test:int
        env:
          CI: true
      - name: Deploy
        # Only try and deploy on merged code
        if: "github.ref_name == 'main' && (github.event_name == 'push' || github.event_name == 'schedule')"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./public # The folder the action should deploy.
          branch: pages
      - run: npm run test:links
        env:
          CI: true
